### ISSUE TITLE
RESTHeart: Anmeldung über MongoDB-Nutzer

### ISSUE THREAD

**Issue by spegenau** [Data-City/MongoDB-Rest#1]
Es soll möglich sein, sich über MongoDB-User bei RESTHeart anzumelden.

Beispiel:
In Datenbank admin liegen alle User. Wenn man RESTHeart im Browser öffnet und zur Authentifizierung aufgefordert wird, prüft RESTHeart Benutzername und Passwort gegen die admin Datenbank

**Comment by ZiZiWang** [comment]
Ich hab einfach den Benutzername und das Passwort, die in admin DB abgelegt wurden, in den USERS Teil(a:a) der Security Config-Datei(/etc/security.yml) von Restheart eingesetzt. Um RESTHeart Benutzername und Passwort gegen die admin Datenbank zu prüfen, muss man die restheart config-Datei dynamisch einstellen. Wenn der Teil "mongo-credentials" der Config-Datei (/etc/restheart.yml) es ablesen kann, was man bei der Einlog Konsole über den Browser den Benutzername und das Passwort eingegeben hat, verbindet Restheart durch die eingegebenen Benutername und Passwort auf dem Mongodb. ：（
