### ISSUE TITLE
Skalierungsmöglichkeiten?

### ISSUE THREAD

**Issue by Nullmann** [Data-City/MongoDB-Rest#11]
Kann man auf die Werte Funktionen schmeißen? Also mit einem Wert, z.B. 0,5; log2() oder ln()

Denkbar wären verschiedene Funktionsaufrufe:
scaleNumber(columnName, Wert) --> scaleNumber(beispiel.klassen, 0,5) --> Multipliziert alle Werte mit 0,5
scaleLog(columnName) --> scaleLog(beispiel.klassen) --> Berechnet 2er-Log von den Werten
scaleLn(columnName) --> scaleLn(beispiel.klassen) --> Berechnet ln() von den Werten

**Comment by Nullmann** [comment]
Wurde von Linh auf WebGL-Basis bereits implementiert.

**Comment by thuylinhluu** [comment]
Vielleicht kann mir das ja jemand erklären, wie ihr euch das gedacht hattet? Ich hatte es so verstanden, dass ich euch sage, dass der Nutzer gerne skalieren möchte. Dann würdet ihr die entsprechende Spalte skalieren... und dann?

Falls das Bild neu gezeichnet werden sollte mit drawCity(...), dann habe ich ja nicht mehr die alten Werte, d.h. in der Legende würde bei Klassen, Methoden, etc. ebenfalls die skalierten Zahlen angezeigt werden - und das wollen wir doch nicht, oder?

Aber vielleicht hab ich die Idee auch einfach nicht verstanden.
