### ISSUE TITLE
allowDiskUse mit RESTHeart

### ISSUE THREAD

**Issue by spegenau** [Data-City/MongoDB-Rest#13]
Unterstützt RESTHeart den allowDiskUse Parameter?

Ziel ist es Engpääse bei der Pipeline zu umgehen

https://docs.mongodb.org/v3.0/reference/method/db.collection.aggregate/#db.collection.aggregate

**Comment by ZiZiWang** [comment]
Laut Sourcecode Zeilen131-140 von Restheart(https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/handlers/aggregation/GetAggregationHandler.java) wird der allowDiskUse Parameter nicht unterstzürtzt.  Die Aggregartion von Restheart hat nur auf Pipeline Aggregation Stages beobachtet(https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/hal/metadata/AggregationPipeline.java)
