### ISSUE TITLE
RESTHeart mit JBoss

### ISSUE THREAD

**Issue by spegenau** [Data-City/MongoDB-Rest#5]
Ziel ist es, RESTHeart so zu verpacken, dass es in JBoss (bzw. vor allem gemäß Blueprint) laufen kann.

**Comment by MarcelMP** [comment]
Hierzu könnte unter anderem folgender Link nützlich sein. Damit könnten wir schon mal das Projekt packen. Unterpunkt: Using the Maven shade plugin:
https://softinstigate.atlassian.net/wiki/display/RH/Custom+Access+Manager#CustomAccessManager-UsingtheMavenshadeplugin

**Comment by ZiZiWang** [comment]
Leider wurde es nicht realisiert. Weil das Restheat auf dem Undertow aufgebaut wird. Wenn man es auf JBoss legen möchte, muss man die Sourcecode von Restheart verändern. Und die Erstellung der xml Daten ist auch sehr schwierig.
