### ISSUE TITLE
RESTHeart liefert Client aus

### ISSUE THREAD

**Issue by spegenau** [Data-City/MongoDB-Rest#6]
RESTHeart beherrscht es scheinbar auch, statische Inhalte (HTML/JavaScript) auszuliefern. 

Ziel ist es, dass RESTHeart auch die Dateien ausliefert, die zum Anzeigen des Clients nötig sind. 

Cool wäre dabei ein Skript, dass automatisch alles packt.

**Comment by spegenau** [comment]
https://softinstigate.atlassian.net/wiki/display/RH/Advanced+Configuration
Unterpunkt: Static Resources

Bitte teste mal lokal, ob man so vernünftig den dist/-Ordner ausliefern kommen.

**Comment by ZiZiWang** [comment]
1. Clone des Projekts
   git clone https://github.com/Data-City/client.git 
2. Install Dependencies
   cd client
   npm install
   bower install
3. Änderung der Konfigurationsdatei
   (  - what: dist
     where: /test
     welcome-file: index.html
     secured: false
     embedded: false
   in static-resources-mounts hinzufügen
   und  das Verzeichnis von idm und access-manager  zu verändern)
   Kopieren restheart.jar in /client
   Kopieren restheart.yml und restheart-security.yml, die auf Trello hochgeladen wurden, in /client
4. Laufen der mongod und restheart
   java -server -jar restheart.jar restheart.yml
5. Web Client wird jetzt durch 127.0.0.1:8080/test/ ausgeliefert
