### ISSUE TITLE
Sicherstellen, dass alle Felder in jedem Document sind

### ISSUE THREAD

**Issue by spegenau** [Data-City/MongoDB-Rest#7]
Um alle Felder einer Collection zu identifizieren, werte ich einen Eintrag (Document) der Collection aus.

Bitter sicherstellen, dass in jedem Document alle Felder enthalten sind.

Beispiel:
Zeile in CSV-Datei: x.y.z,1,,3
Soll (ungefähr) in diesem JSON resultieren:
{
  "Package": "x.y.z",
  "Klassen": 1,
  "Attribute": null,
  "Zeilen": 3
}

Dabei ist egal, was in Attribute (dem leeren Feld der CSV-Zeile) steht, hauptsache "Attribute" ist da.

**Comment by thuylinhluu** [comment]
da sollten wir uns noch vielleicht drauf einigen, ob da null oder "" steht (leerer String). Beim letzten JSON standen da leere Strings. Das war auch okay...

**Comment by ZiZiWang** [comment]
Die Attribute wird immer da sein. Es steht ein "" nach der Attribute.
